"""Initial migration.

Revision ID: bd83c141da20
Revises: 
Create Date: 2024-06-18 14:48:24.773258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd83c141da20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('paragraph', sa.Text(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('parent_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_option_id'], ['option.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    op.drop_table('story')
    # ### end Alembic commands ###
