"""Create initial tables

Revision ID: e503ebf63747
Revises: bd83c141da20
Create Date: 2024-06-18 14:50:58.060153

This revision was autogenerated as a duplicate of bd83c141da20, which already
creates the story and option tables. Running its original body against a fresh
database failed with "relation 'story' already exists", so it is now a no-op.
It stays in the chain to keep databases already stamped at this revision valid.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e503ebf63747'
down_revision = 'bd83c141da20'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    pass
